---
deployment:
  tasks:
    - mkdir -p $HOME/public_html/cyberoxtech.com
    - /bin/cp -r . $HOME/public_html/cyberoxtech.com/
    - /bin/rm -rf $HOME/public_html/cyberoxtech.com/.git $HOME/public_html/cyberoxtech.com/.cpanel.yml $HOME/public_html/cyberoxtech.com/cyberoxtech-website-deploy.zip
