---
deployment:
  tasks:
    - echo "Starting deployment"
    - echo "Home is $HOME"
    - echo "PWD is $(pwd)"
    - ls -la
    - mkdir -p /home/sites/38a/4/4b4620aad9/public_html/cyberoxtech.com
    - /bin/cp -r . /home/sites/38a/4/4b4620aad9/public_html/cyberoxtech.com/
    - /bin/rm -rf /home/sites/38a/4/4b4620aad9/public_html/cyberoxtech.com/.git
    - /bin/rm -f /home/sites/38a/4/4b4620aad9/public_html/cyberoxtech.com/.cpanel.yml
    - echo "Deployment complete"
    - ls /home/sites/38a/4/4b4620aad9/public_html/cyberoxtech.com/
